apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sr-hybrid

resources:
  - namespace.yaml
  - storage-pvc.yaml
  - sr-hybrid-blue-deployment.yaml
  - sr-hybrid-green-deployment.yaml
  - sr-hybrid-service.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
