apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sr-hybrid
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'sr-hybrid'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - sr-hybrid
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: sr-hybrid
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_version]
            target_label: version
          - source_labels: [__address__]
            target_label: __address__
            regex: ([^:]+)(?::\d+)?
            replacement: $1:8080

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
