apiVersion: v1
kind: Service
metadata:
  name: sr-hybrid
  namespace: sr-hybrid
  labels:
    app: sr-hybrid
spec:
  type: ClusterIP
  selector:
    app: sr-hybrid
    version: blue  # initial color; GitHub Actions will patch between blue/green
  ports:
    - name: http
      port: 8080
      targetPort: 8080
