apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-hybrid-storage
  namespace: sr-hybrid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
