apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-hybrid-data-pvc
  namespace: sr-hybrid
  labels:
    app: sr-hybrid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sr-hybrid-logs-pvc
  namespace: sr-hybrid
  labels:
    app: sr-hybrid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
